### PR TITLE
Update dev packages so that Laravel 6 can be pulled in

### PR DESCRIPTION
**Pull request by ssfinney**
- Updated dev packages
- Use `Str::finish()` instead of the deprecated `str_finish()` method

Addresses #16

### CODE REVIEW

**Comment by jimmypuckett** [comment]
You are going to have to leave the old version there as an option to keep supporting older versions on Laravel.

**Comment by ssfinney** [comment]
@jimmypuckett No, Laravel 5.5 supports `Str::finish` also: https://laravel.com/api/5.5/Illuminate/Support/Str.html

**Comment by ssfinney** [comment]
@jimmypuckett This is ready.

**Comment by jimmypuckett** [comment]
I was not talking about the facade. I was referencing the composer versions. You got the failed test about the same time that I posted.

Thanks for getting this fixed up.

**Pull request merged**
