### PR TITLE
Allow Laravel 6.0 in composer.json

### PR DESCRIPTION
**Pull request by lucasdcrk**

### CODE REVIEW

**Comment by jimmypuckett** [comment]
@lucasdcrk, thanks for the PR, since 6 is not officially released, the tests are not running against 6 of the illuminate libraries.  We will let them come out tomorrow & then run the tests to make sure that everything is good & then merge.

**Comment by lucasdcrk** [comment]
Ok no problem ;)

**Comment by lucasdcrk** [comment]
Any news on this?

**Comment by jimmypuckett** [comment]
@lucasdcrk , I am sorry that we did not get this done. I am at a conference & totally forgot about it.  I just triggered the builds, so as soon as they pass with 6, I will merge & tag.

**Comment by jimmypuckett** [comment]
OK, 2.2.0 has been tagged.

Thanks for your help!

**Comment by jimmypuckett** [comment]
@lucasdcrk, I don't think that the PR did what you wanted. I am seeing that the version of illuminate is still version 5.x.  I think that there is a dependency in there that is holding it back.  I digging into what package is holding it back.

**Comment by ssfinney** [comment]
@jimmypuckett Illuminate\Support requires Carbon v2, but something is stopping us from upgrading it. I'm looking at that now.

**Comment by jimmypuckett** [comment]
That is hitting our other packages too. I started branches on all of them last night & found this.


On Sep 6, 2019, at 09:35, Stephen Finney <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimmypuckett<https://github.com/jimmypuckett> Illuminate\Support requires Carbon v2, but something is stopping us from upgrading it. I'm looking at that now.

**Comment by ssfinney** [comment]
@jimmypuckett `symfony/var-dumper` and `psy/psysh` needed to be upgraded too. I'm going to push that to another PR.

**Comment by ssfinney** [comment]
Hey @lucasdcrk, we tagged a new version `2.2.1` that should do the trick for you!

**Comment by lucasdcrk** [comment]
Thanks @ssfinney @jimmypuckett ^^

**Pull request merged**
