### PR TITLE
Feature/support5.6

### PR DESCRIPTION
**Pull request by jimmypuckett**
Again, let's bump major when we tag release.

### CODE REVIEW

**Comment by tatarko** [comment]
Hi guys, is there anything new about this pull request? I would like to update my Laravel project to 5.6 and this package is blocking me from doing so.

**Comment by jimmypuckett** [comment]
@ssfinney are you tagging a realse? I’m in a meeting until this afternoon.

**Comment by ssfinney** [comment]
@jimmypuckett Yep, tagging it now.

**Comment by ssfinney** [comment]
@jimmypuckett I'm bumping minor, not major. So I'll tag at 1.3.0, not 2.0.0.

**Comment by ssfinney** [comment]
@tatarko Thanks for reminding us about this! Laravel 5.6 support has been released as part of the new 1.3.0 tag.

**Comment by tatarko** [comment]
@ssfinney thank you ;)

**Pull request merged**
