### PR TITLE
Fix logout listener

### PR DESCRIPTION
**Pull request by trippo**
This is a fix to get logout work. 
It is necessary to insert in the services.php the api.key key generated in forum admin as "All user key" and the api.user the username of admin user (see this guide https://meta.discourse.org/t/how-to-create-an-api-key-on-the-admin-panel/87383)

### CODE REVIEW

**Comment by ssfinney** [comment]
Hi @trippo! Thanks for contributing. May I ask why you've closed this? Did you find that this wasn't necessary, or something else?

**Comment by trippo** [comment]
reopen

**Comment by ssfinney** [comment]
@trippo What use case are you trying to solve? We are able to logout our app from Laravel -> Discourse. So, if we logout in Laravel, our Discourse session is logged out too. 

And if we logout from Discourse, we are redirected back to Laravel (but not logged out of Laravel). Are you wanting to automatically log out the Laravel session also?

**Comment by ssfinney** [comment]
Done in #23 already

**Pull request closed without merging**
