### PR TITLE
Update to support Laravel 9

### PR DESCRIPTION
**Pull request by jtolj**

### CODE REVIEW

**Comment by jimmypuckett** [comment]
@jtolj Thanks for this PR.  Running the tests now.  If passes, I will merge in a few.

**Comment by jimmypuckett** [comment]
Ok, merged to development.  I am starting a quick branch to support PHP 8.  If it goes well in the next 10/15 min, I will merge it too & tag.  If not, then I will just tag your changes.

**Comment by jimmypuckett** [comment]
Tagged 2.6.0.  I ran into some issues with testing in 8, so tagged your PR.

**Comment by jtolj** [comment]
@jimmypuckett Thanks so much! Sorry about that. I did run the PHPUnit tests with 8.1, but not your full CI build. Let me know if there's anything I can do to help - your package has saved me tons of time 😃 .

**Pull request merged**
